import Head from 'next/head'
import Bannner from '../components/Banner/Bannner'
import Image from 'next/image'

import heroImage from "../public/static/hero-image.png"
import Card from '../components/Card/card'
// import { fetchData } from '../lib/coffeestores'
import useLoaction from './../hooks/useLoaction';


export async function getStaticProps(context) {
  const options = {
    method: 'GET',
    headers: {
      accept: 'application/json',
      Authorization: process.env.PLACE_API
    }
  };

  const res = await fetch('https://api.foursquare.com/v3/places/search', options)
    .then(response => response.json())
    .then(data => data.results)
  console.log(res)
  // const data = await res.results

  return {
    props: {
      cofffeeStores: res,
    }
  }
}

export default function Home({ cofffeeStores }) {
  const { handleLoaction,latLong,loactionError,isFindingLoaction } = useLoaction()
  console.log(cofffeeStores.categories)
  const handleBannerClick = () => {
    !isFindingLoaction &&  handleLoaction()
    console.log({latLong,loactionError})
  }

  return (
    <>
      <Head>
        <title>Coffee Connnoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.pngkey.com/png/full/453-4536090_coffe-cup-png.png" />
      </Head>

      <main className='mb-10'>
        <Bannner handleOnClick={handleBannerClick} buttonText={isFindingLoaction? "Loacting" : "View Stores"}/>
        <div className='absolute top-10 left-40'>
          <Image src={heroImage} width={900} height={400} />
        </div>
        {
          cofffeeStores &&
          <div className='flex flex-col'>
            <h2 className='ml-10 text-xl mb-5'>Jedda Coffee Stores</h2>
            <div className="grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 ml-10">
              {
                cofffeeStores.map(item => {
                  {/* console.log(item.categories.icon) */ }
                  return <Card
                    key={item.fsq_id}
                    title={item.name}
                    imgUrl={item.icon}
                    href={`coffee-store/${item.fsq_id}`}
                  />
                })
              }
            </div>
          </div>
        }
      </main>
    </>
  )
}
