import Head from 'next/head'
import Bannner from '../components/Banner/Bannner'
import Image from 'next/image'

import heroImage from "../public/static/hero-image.png"
import Card from '../components/Card/card'

import cofffeeStores from "../data/coffee-stores.json"

export default function Home() {
  const handleBannerClick = () => {

  }
  console.log(cofffeeStores)
  return (
    <>
      <Head>
        <title>Coffee Connnoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.pngkey.com/png/full/453-4536090_coffe-cup-png.png" />
      </Head>

      <main className='mb-10'>
        <Bannner handleOnClick={handleBannerClick} buttonText="Find Stores" />
        <div className='absolute top-10 left-40'>
          <Image src={heroImage} width={900} height={400} />
        </div>
        <div className="grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 ml-10">
          {
            cofffeeStores.map(item => (
              <Card
                title={item.name}
                imgUrl={item.imgUrl}
                href={`coffee-store/${item.id}`}
              />
            ))
          }

        </div>
      </main>
    </>
  )
}
